### PR TITLE
A full refacto of `openDBChannel` based on our latest discoveries.

### PR DESCRIPTION
**Pull request by louisameline**

### CODE REVIEW

**Comment by mesqueeb** [comment]
I think, without that small change, it would break if someone does:

```js
dispatch('someModule/openDBChannel', null, { root: true })
```

In this case `null` is actually passed as the `parameters` so it throws an error
> "can't read clauses of undefined"

on the next line.


You're probably thinking "why in the world would someone pass `null`, which I thought so myself, but it's the official Vuex docs that actually have that pattern show in their examples...

Screenshot 2020-07-25 12 49 31

So yeah, we gotta think that some ppl will also pass `null` where we expect only either an object or `undefined`.

**Comment by louisameline** [comment]
Right, I overlooked the compatibility code block, but this line can actually also go away when we get rid of it, so it could be moved inside of it.

**Comment by louisameline** [comment]
This has to get merged, please don't let it rot until it has annoying conflicts again.

**Comment by mesqueeb** [comment]
Doing some final tests related to multiple tabs with a user today!

**Pull request merged**
